name: Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "release/**"]
    types: ["opened", "reopened", "synchronize"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run Unit Tests
    runs-on: macos-26
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Get Swift Version
        run: swift --version
      - name: Run Unit Tests
        run: swift Scripts/RunUnitTests.swift >> "$GITHUB_STEP_SUMMARY"
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage
          path: .build/code-coverage/
          include-hidden-files: true
          if-no-files-found: error
